version: '3.9'
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - next-app:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
