name: Storybook CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 依存関係のインストール
      - name: Install dependencies
        run: npm install

      # 4. Playwright のブラウザをインストール
      - name: Install Playwright Browsers
        run: npx playwright install

      # 5. Storybook テストランナーの実行
      - name: Run Storybook Test Runner
        run: npm run test-storybook

      # 6. Storybook のビルド
      - name: Build Storybook
        run: npm run build-storybook

      # 7. GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: storybook-static
